#!/bin/bash
set -e
echo "# MISSING: IMG_5001.PNG (no match in public)"
echo "# MISSING: IMG_5006.PNG (no match in public)"
echo "# MISSING: IMG_5003.PNG (no match in public)"
echo "# MISSING: IMG_5004.PNG (no match in public)"
echo "# MISSING: IMG_5005.PNG (no match in public)"
echo "# MISSING: img_5001.png (no match in public)"
echo "# MISSING: img_5003.png (no match in public)"
echo "# MISSING: img_5004.png (no match in public)"
echo "# MISSING: img_5005.png (no match in public)"
echo "# MISSING: img_5006.png (no match in public)"
echo "# MISSING: img_5007.png (no match in public)"
echo "# MISSING: fibo-logo.png (no match in public)"
echo "# MISSING: fibo-poster-2.png (no match in public)"
echo "# MISSING: fibo-poster.png (no match in public)"
echo "# MISSING: fibo-socials.png (no match in public)"
echo "# MISSING: fibo-straat.png (no match in public)"
echo "# MISSING: doosal.png (no match in public)"
echo "# MISSING: krabbels.jpg (no match in public)"
echo "# MISSING: partii.png (no match in public)"
sed -i '' 's/spelen\.png/\/spelen.png/g' "app/project-3/page.tsx"
sed -i '' 's/spelen\.png/\/spelen.png/g' "app/project3/page.tsx"
echo "# MISSING: bts.png (no match in public)"
echo "# MISSING: fibo%20logo.png (no match in public)"
echo "# MISSING: fibo%20poster%202.png (no match in public)"
echo "# MISSING: fibo%20poster.png (no match in public)"
echo "# MISSING: fibo%20socials.png (no match in public)"
echo "# MISSING: fibo%20straat.png (no match in public)"
sed -i '' 's/poster\.png/\/poster.png/g' "app/project-2/page.tsx"
sed -i '' 's/poster\.png/\/poster.png/g' "app/project2/page.tsx"
sed -i '' 's/poster\.png/\/poster.png/g' "app/project2 copy/page.tsx"
echo "# MISSING: doosAl.png (no match in public)"
echo "# MISSING: Bts.png (no match in public)"
echo "# MISSING: wereldbol.png (no match in public)"